### ISSUE TITLE
Untraceable origin of code, can't figure out what changes can be backported

### ISSUE THREAD

**Issue by sofar** [jordan4ibanez/open_minecart#2]
You didn't start with a clean fork or copy of the code in minetest_game, so there's no way to easily compare the changes and improvements you're making. Are you interested in seeing if any of the changes can be merged back in boost_cart or minetest_game? Because it's going to be really hard to do so. The first 2 commits are basically history wipes.

**Comment by jordan4ibanez** [comment]
Are you interested in seeing if any of the changes can be merged back in boost_cart or minetest_game?

Not at all, this is a rewrite of the code, the mod can be replaced by my implimentation, Minetest as an entity (https://github.com/minetest/minetest) and all of the devs that work here should sample, clone, copy, improve, etc my code and drop it into minetest-game as they see fit, I permit all usage of anyone or anything, private or monetized to use this in any way. (cc0)

**Comment by sofar** [comment]
Seems solved now, so, I don't see any issues.
