### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sofar** [jordan4ibanez/open_minecart#3]
the carts version in minetest_game has an MIT license, and it looks like code was copied from it. You also state that the code is a rewrite from that, but the MIT license is missing as well as the required copyright attribution.

**Comment by jordan4ibanez** [comment]
Actually all this code was copied from open_ai and was written from scratch, but I did use the assets from carts, so I'll look into that

**Comment by jordan4ibanez** [comment]
https://github.com/jordan4ibanez/open_minecart/blob/master/license.txt Is this satisfactory?

**Comment by sofar** [comment]
for the textures, you should credit PixelBOX(WTFPL) directly, not minetest_game.
